In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import zipfile

In [0]:
with zipfile.ZipFile("gdrive/My Drive/Reviews.csv.zip","r") as zip_ref:
    zip_ref.extractall()

In [0]:
import numpy as np
import pandas as pd

In [0]:
df= pd.read_csv("Reviews.csv")

In [0]:
df.shape

(568454, 10)

In [0]:
df.sample(frac=1)

In [0]:
data_set=df[:100000]

In [0]:
data_set.head()

Id  ...                                               Text
0   1  ...  I have bought several of the Vitality canned d...
1   2  ...  Product arrived labeled as Jumbo Salted Peanut...
2   3  ...  This is a confection that has been around a fe...
3   4  ...  If you are looking for the secret ingredient i...
4   5  ...  Great taffy at a great price.  There was a wid...

[5 rows x 10 columns]

In [0]:
data_set.drop(['Id','ProductId','UserId','HelpfulnessNumerator','HelpfulnessDenominator','ProfileName','Time'], axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [0]:
data_set.head()

Score  ...                                               Text
0      5  ...  I have bought several of the Vitality canned d...
1      1  ...  Product arrived labeled as Jumbo Salted Peanut...
2      4  ...  This is a confection that has been around a fe...
3      2  ...  If you are looking for the secret ingredient i...
4      5  ...  Great taffy at a great price.  There was a wid...

[5 rows x 3 columns]

In [0]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 5 columns):
HelpfulnessNumerator      568454 non-null int64
HelpfulnessDenominator    568454 non-null int64
Score                     568454 non-null int64
Summary                   568427 non-null object
Text                      568454 non-null object
dtypes: int64(3), object(2)
memory usage: 21.7+ MB


In [0]:
data_set.isnull().sum()

Score      0
Summary    2
Text       0
dtype: int64

In [0]:
data_set.dropna(axis=0,how='any',inplace=True)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 568427 entries, 0 to 568453
Data columns (total 5 columns):
HelpfulnessNumerator      568427 non-null int64
HelpfulnessDenominator    568427 non-null int64
Score                     568427 non-null int64
Summary                   568427 non-null object
Text                      568427 non-null object
dtypes: int64(3), object(2)
memory usage: 26.0+ MB


In [0]:
data_set.isnull().sum()

HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Summary                   0
Text                      0
dtype: int64

In [0]:
data_set['Score'].unique()

array([5, 1, 4, 2, 3])

In [0]:
l=[]
for i in data_set['Text']:
  l.append(len(i.split()))

max(l)

2520

In [0]:
#data_set['Helpfulness']= data_set['HelpfulnessNumerator'] + data_set['HelpfulnessDenominator']

In [0]:
data_set.head()

In [0]:
data_set[data_set['Score']==3]

In [0]:
def polarity(x):
    if x < 3:
        return 'Negative'
    if x==3:
        return 'Neutral'
    else:
        return 'Positive'

In [0]:
data_set['Sentiment']=data_set['Score'].map(polarity)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
data_set[data_set['Score']==3]

In [0]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
eng_stopwords = set(stopwords.words("english"))


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
data_set['Review'] = data_set['Text'].str.replace('[^\w\s]','')

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
data_set.head()

In [0]:
data_set['Review']=data_set['Review'].apply(lambda x:[item for item in x.split() if item not in eng_stopwords])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
data_set.head()

In [0]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [0]:
from nltk.stem import WordNetLemmatizer

In [0]:


def preprocess_data(X):
    preprocessed_data=[]
    lemma = WordNetLemmatizer()
    for text in X:
        #print(text)
        text = text.lower()
        #text = text.translate(trans_punc)
        text = [lemma.lemmatize(word) for word in text.split()]
        text = [x for x in text if not any(c.isdigit() for c in x)]
        preprocessed_data.append(' '.join(text))
        #print(text)

    return preprocessed_data

In [0]:
data_set['lem_Review']=data_set['Review'].apply(preprocess_data)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
#data_set['lem_Review']
l=[]
for i in data_set['lem_Review']:
  l.append(len(i))
  
max(l)


1665

In [0]:
ser=pd.Series(l)

In [0]:
ser.describe()

count    99998.000000
mean        47.619212
std         47.096945
min          5.000000
25%         20.000000
50%         33.000000
75%         58.000000
max       1665.000000
dtype: float64

In [0]:
nltk.stem.WordNetLemmatizer().lemmatize('buying')

'buying'

In [0]:
data_set['Review']=data_set['lem_Review'].apply(lambda x: " ".join(x))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [0]:
#data_set['Len_review']=data_set['lem_Review'].apply(lambda x: len(x))

In [0]:
data_set['Review'].nunique()

393030

In [0]:
import keras
import tensorflow as tf
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.regularizers import L1L2


from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error


Using TensorFlow backend.


In [0]:
token= Tokenizer()
token.fit_on_texts(data_set['Review'])
encoded_lines = token.texts_to_sequences(data_set['Review'])

In [0]:
number_of_words = len(token.word_index) + 1
Review_max_length_of_input = 100
embedding_vector_length = 128

In [0]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

In [0]:
target=data_set['Sentiment']
encoder = LabelEncoder()
encoder.fit(target)
encoded_Y = encoder.transform(target)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [0]:
data = sequence.pad_sequences(encoded_lines, Review_max_length_of_input)
X_train, X_test, y_train, y_test = train_test_split(data,dummy_y, test_size=0.2, random_state=13)

In [0]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train,y_train, test_size=0.2, random_state=13)

In [0]:
X_train.shape, X_valid.shape, X_test.shape

((63998, 100), (16000, 100), (20000, 100))

In [0]:
y_train.shape , y_valid.shape , y_test.shape

((63998, 3), (16000, 3), (20000, 3))

In [0]:
adagrad=keras.optimizers.Adagrad(lr=0.01, epsilon=None, decay=0.0)

In [0]:
model = Sequential()
model.add(Embedding(number_of_words, embedding_vector_length, input_length = Review_max_length_of_input))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2, return_sequences=True))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2, return_sequences=True))
model.add(LSTM(50))
model.add(Dense(3, activation = 'softmax'))
model.compile(loss='categorical_crossentropy', optimizer= adagrad, metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 100, 128)          10339072  
_________________________________________________________________
lstm_4 (LSTM)                (None, 100, 100)          91600     
_________________________________________________________________
lstm_5 (LSTM)                (None, 100, 100)          80400     
_________________________________________________________________
lstm_6 (LSTM)                (None, 50)                30200     
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 153       
Total params: 10,541,425
Trainable params: 10,541,425
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.fit(X_train, y_train, batch_size = 1024, epochs = 20, validation_data=(X_valid, y_valid),verbose = True)

Train on 63998 samples, validate on 16000 samples
Epoch 1/20
63998/63998 [==============================] - 59s 928us/step - loss: 0.6209 - acc: 0.7847 - val_loss: 0.4827 - val_acc: 0.8274
Epoch 2/20
63998/63998 [==============================] - 57s 886us/step - loss: 0.4147 - acc: 0.8499 - val_loss: 0.4506 - val_acc: 0.8396
Epoch 3/20
63998/63998 [==============================] - 57s 885us/step - loss: 0.3506 - acc: 0.8706 - val_loss: 0.4417 - val_acc: 0.8417
Epoch 4/20
63998/63998 [==============================] - 56s 883us/step - loss: 0.2997 - acc: 0.8903 - val_loss: 0.4299 - val_acc: 0.8471
Epoch 5/20
63998/63998 [==============================] - 57s 886us/step - loss: 0.2530 - acc: 0.9096 - val_loss: 0.4634 - val_acc: 0.8479
Epoch 6/20
63998/63998 [==============================] - 57s 884us/step - loss: 0.2195 - acc: 0.9228 - val_loss: 0.4981 - val_acc: 0.8289
Epoch 7/20
63998/63998 [==============================] - 57s 883us/step - loss: 0.1922 - acc: 0.9351 - val_loss: 0.

In [0]:
output = model.predict(X_test, 1024)

In [0]:
output[0]

array([0.00152049, 0.00171378, 0.99676573], dtype=float32)

In [0]:
output.shape , y_test.shape

((60000,), (20000, 3))

In [0]:
from sklearn import metrics
print(metrics.accuracy_score(y_test.argmax(axis=1), output.argmax(axis=1)))

0.83405


In [0]:
y_test[0], output.argmax(axis=1)

(array([0., 0., 1.], dtype=float32), array([2, 2, 2, ..., 2, 1, 2]))

In [0]:
confusion = metrics.confusion_matrix(y_test.argmax(axis=1), output.argmax(axis=1))

In [0]:
confusion

array([[ 1909,   308,   731],
       [  350,   537,   753],
       [  631,   546, 14235]])